### ISSUE TITLE
直接定义 debug 版本的 url 不好么?

### ISSUE THREAD

**Issue by Pikaurd** [PonyCui/NSEtcHosts#1]
好奇的问一下, 恕我愚昧没看出这样的好处, 还望指教

**Comment by PonyCui** [comment]
1.当你在内网开发时，你不可能指定一个debug版本的域名（当然，如果你可以在内网搭建一个DNS服务器或者已经绑定hosts的HTTP代理服务器，也可以做到）。
2.大型项目一般会有集群服务器，亦即，同一服务器代码遍布在超过2台以上的服务器，当你需要指定到某台服务器时，绑host就是最好的方法。

**Comment by Pikaurd** [comment]
thx
